### ISSUE TITLE
Support for custom port

### ISSUE THREAD

**Issue by rthatipa** [fynydd/sqribe#2]
Currently the port is hard coded to `1433`. Is it possible to include a parameter `port` to pass the custom port number

eg:
`> sqribe backup /data_source:"server=localhost;port=2020;database=AdventureWorks2017;user id=aw2017user;password='abracadabra';" /objects:"all" /output_path:"~/Desktop/sqribe-backup"
`

**Comment by argentini** [comment]
> Currently the port is hard coded to `1433`. Is it possible to include a parameter `port` to pass the custom port number
> 
> eg:
> `> sqribe backup /data_source:"server=localhost;port=2020;database=AdventureWorks2017;user id=aw2017user;password='abracadabra';" /objects:"all" /output_path:"~/Desktop/sqribe-backup" `

The port should be specified in the connection string using comma syntax, like: "server=localhost,2020;..."
