### ISSUE TITLE
Checking connection to database server ➜  DATABASE IS UNAVAILABLE!

### ISSUE THREAD

**Issue by kaisiyun** [fynydd/sqribe#3]
sqribe for openEuler 提示如下错误，同一网络下的Windows 10里可以正常备份数据库。
Linux 已经安装了 [ODBC Driver 18 for SQL Server]
Press [Y] or [ENTER] to backup, any other key to cancel…
  (press [Control]+[C] or [Esc] to abort the backup at any time)
  • Checking network ➜  OK
  • Checking connection to database server ➜  DATABASE IS UNAVAILABLE!
  BACKUP PROCESS ABORTED!
  Backup aborted on 周三-29-6月-2022 @ 9:34 下午
  Total time: 0s

**Comment by argentini** [comment]
.NET 6 internals are used to connect to the database. So your connection string may not be valid.

**Comment by argentini** [comment]
That connection string may not work in Linux. Did you try passing the port to the server (e.g. 10.0.1.3,1433)? Perhaps try a MS SQL tool on Linux (like MS Azure Studio) and verify the connection string works in Linux.

**Comment by kaisiyun** [comment]
Feel your reply, the problem has been resolved.
I tried to install dotnet and Microsoft ODBC Driver for SQL Server (Linux) in openEuler, and then connected to another MSSQL2016. thank you
