### ISSUE TITLE
Sqribe is suitable for cloud server backup database.

### ISSUE THREAD

**Issue by kaisiyun** [fynydd/sqribe#4]
Sqribe is suitable for cloud server backup database.

My usage scenario is that there are about 20 databases running in the cloud server, which are backed up to the local Linux server once a week. Testing a library in Windows 10 took 10 hours, backed up about 3.5 GIGABytes of data, and wasn't done yet.

**Comment by argentini** [comment]
I don't understand. What are you asking?

**Comment by kaisiyun** [comment]
is Sqribe suitable for cloud server backup database ?

My usage scenario is that there are about 20 databases running in the cloud server, which are backed up to the local Linux server once a week. Testing a library in Windows 10 took 10 hours, backed up about 3.5 GIGABytes of data, and wasn't done yet.

**Comment by argentini** [comment]
SQribe does work with Azure and AWS RDS SQL Server databases. But keep in mind that during a backup operation it generates the data scripts on the SQL Server itself. So server memory could be a bottleneck with backing up large data sets. You can configure your backup to skip specific tables that have data you don't need to back up (like log data).

**Comment by kaisiyun** [comment]
I test an offline Dell R730XD server
The E52603V4/32 GB memory is configured
The size of the manually backed up MSSQL data file is 13.5 GB
After qrribe backup is enabled, all CPU and memory resources of the server are occupied
The system is stuck and the ERP client is disconnected
why is this ?

**Comment by argentini** [comment]
Make sure the SQL Server instance is allocated plenty of memory.

**Comment by argentini** [comment]
@kaisiyun Also, the newest version of SQribe, 1.7, now generates the date insert scripts on your local machine, so this potential bottleneck no longer exists.
