### ISSUE TITLE
Timeout during datbase backup

### ISSUE THREAD

**Issue by louisjrdev** [fynydd/sqribe#6]
I tried to backup one of my azure sql databases and after about 2 minutes it just stops and says aborted for the tasks 1 by one. 

When I check the log this seems to be because of a timeout, could we make this a configurable timeout perhaps?

<img width="805" alt="image" src="https://github.com/fynydd/sqribe/assets/17555062/1efa43c7-ac80-4f77-a5dc-67a635817670">

**Comment by argentini** [comment]
It should honor the timeout in the connection string. Give that a go. I also created a new project named [SqlPkg](https://github.com/argentini/Argentini.SqlPkg) that may be a better fit.
